### ISSUE TITLE
 Issue with Argument File Parsing in Repository

### ISSUE THREAD

**Issue by Priyakarna13** [gitter-lab/nn4dms#11] opened 2024-11-08 13:15 UTC
Hi,
I am reaching out because I encountered an error while trying to modify the parameters in the example.txt file to experiment with different train-tune-test split values. I adjusted the train_size, tune_size, and test_size values to 0.7, 0.2, and 0.1 respectively, expecting them to sum to 1 as required. However, I received the following errors-

![image](https://github.com/user-attachments/assets/3c8850b6-638b-480f-b05c-20046e684fc2)
![image (1)](https://github.com/user-attachments/assets/0bb9e9b7-35b5-4f8b-bd00-1c753aca8ef7)

I confirmed that the data type for the parsing function in parse_reg_args.py is specified as float. The original example.txt works without issues, but when I modify the values, both the script and the notebook throw this error. I’ve ensured that the format and data type match the requirements, yet the issue persists.

If you have any insights into what might be causing this discrepancy or suggestions for resolving it, I would greatly appreciate your guidance.

Thanks,
Sri

**Comment by agitter** [comment] 2024-11-08 22:12
Thanks for reporting this. I believe it is a bug. The problem is with how floats are stored and added
```
>>> 0.7 + 0.2 + 0.1
0.9999999999999999
```

It should be fixed on this branch https://github.com/gitter-lab/nn4dms/tree/split-float. I'd like @samgelman to review it before merging though.

**Closed as completed** 2024-11-13 18:13 UTC

**Comment by samgelman** [comment] 2024-11-13 18:14
Thanks for the fix @agitter! Let us know if you encounter any additional problems @Priyakarna13.
